# Generated by Django 5.1.1 on 2024-09-25 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("IRON", "IRON"),
                            ("BRONZE", "BRONZE"),
                            ("SILVER", "SILVER"),
                            ("GOLD", "GOLD"),
                            ("PLATINUM", "PLATINUM"),
                            ("EMERALD", "EMERALD"),
                            ("DIAMOND", "DIAMOND"),
                        ],
                        default="IRON",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
