# Generated by Django 5.1.1 on 2024-09-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertomessage',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments',
        ),
        migrations.CreateModel(
            name='FileModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.answertomessage')),
            ],
        ),
        migrations.CreateModel(
            name='FileModelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.message')),
            ],
        ),
        migrations.CreateModel(
            name='LookingRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rivals', models.ManyToManyField(blank=True, related_name='rivals', to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LookingRivalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.profile')),
            ],
        ),
    ]
