# Generated by Django 5.1.1 on 2024-09-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('base', '0002_category'),
        ('teams', '0002_remove_answertomessage_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RivalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderScore', models.FloatField(default=0)),
                ('receiverScore', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.quiz')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverScore', to='accounts.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderScore', to='accounts.profile')),
            ],
        ),
    ]
