# Generated by Django 5.1.1 on 2024-09-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
        ('teams', '0002_remove_team_members_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='files/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerToMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='files/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.message')),
            ],
        ),
    ]
