# Generated by Django 5.1.1 on 2024-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("teams", "0002_alter_team_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="team_members", to="accounts.profile"
            ),
        ),
    ]
