# Generated by Django 5.1.1 on 2024-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_profile_teams"),
        ("teams", "0003_remove_team_members_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="member_teams", to="accounts.profile"
            ),
        ),
    ]
