# Generated by Django 5.1.1 on 2024-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_message_answertomessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='answertomessage',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
