# Generated by Django 5.1.1 on 2024-09-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_filemodel_alter_answertomessage_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.answertomessage')),
            ],
        ),
        migrations.CreateModel(
            name='FileModelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='media/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.message')),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
