# Generated by Django 5.1.1 on 2024-09-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
        ('base', '0001_initial'),
        ('teams', '0005_filemodelanswer_filemodelmessage_delete_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertomessage',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments',
        ),
        migrations.CreateModel(
            name='LookingRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('still_looking', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
