# Generated by Django 5.1.1 on 2024-09-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
        ('teams', '0006_remove_answertomessage_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookingrival',
            name='rivals',
            field=models.ManyToManyField(blank=True, related_name='rivals', to='accounts.profile'),
        ),
    ]
