# Generated by Django 5.1.1 on 2024-09-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
        ('teams', '0007_lookingrival_rivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookingrival',
            name='still_looking',
        ),
        migrations.CreateModel(
            name='LookingRivalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.profile')),
            ],
        ),
    ]
