# Generated by Django 5.1.1 on 2024-09-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_lookingrival_still_looking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookingrival',
            name='subject',
        ),
    ]
