# Generated by Django 5.1.1 on 2024-09-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_rename_funfacts_funfact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funfact",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.subject"
            ),
        ),
    ]
